// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Statement.tsx
import { FragmentLoop } from "./Fragment/FragmentLoop";
import { FragmentAlt } from "./Fragment/FragmentAlt";
import { FragmentPar } from "./Fragment/FragmentPar";
import { FragmentOpt } from "./Fragment/FragmentOpt";
import { FragmentSection } from "./Fragment/FragmentSection";
import { FragmentCritical } from "./Fragment/FragmentCritical";
import { FragmentTryCatchFinally } from "./Fragment/FragmentTryCatchFinally";
import { FragmentRef } from "./Fragment/FragmentRef";
import { Creation } from "./Creation/Creation";
import { Interaction } from "./Interaction/Interaction";
import { InteractionAsync } from "./InteractionAsync/Interaction-async";
import { Divider } from "./Divider/Divider";
import { Return } from "./Return/Return";
import Comment from "../../../../../Comment/Comment";
import { cn } from "@/utils";

export const Statement = (props: {
  context: any;
  origin: string;
  number?: string;
  collapsed?: boolean;
}) => {
  const comment = props.context.getComment() || "";
  const commentObj = new Comment(comment);

  const subProps = {
    className: cn("text-left text-sm text-skin-message", {
      hidden: props.collapsed && !props.context.ret(),
    }),
    context: props.context,
    origin: props.origin,
    comment: comment,
    commentObj: commentObj,
    number: props.number,
  };

  switch (true) {
    case Boolean(props.context.loop()):
      return <FragmentLoop {...subProps} />;
    case Boolean(props.context.alt()):
      return <FragmentAlt {...subProps} />;
    case Boolean(props.context.par()):
      return <FragmentPar {...subProps} />;
    case Boolean(props.context.opt()):
      return <FragmentOpt {...subProps} />;
    case Boolean(props.context.section()):
      return <FragmentSection {...subProps} />;
    case Boolean(props.context.critical()):
      return <FragmentCritical {...subProps} />;
    case Boolean(props.context.tcf()):
      return <FragmentTryCatchFinally {...subProps} />;
    case Boolean(props.context.ref()):
      return <FragmentRef {...subProps} />;
    case Boolean(props.context.creation()):
      return <Creation {...subProps} />;
    case Boolean(props.context.message()):
      return <Interaction {...subProps} />;
    case Boolean(props.context.asyncMessage()):
      return <InteractionAsync {...subProps} />;
    case Boolean(props.context.divider()):
      return <Divider {...subProps} />;
    case Boolean(props.context.ret()):
      return (
        <Return {...subProps} className="text-left text-sm text-skin-message" />
      );
  }
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Statement.vue
<template>
  <!-- Always reset the text alignment for each statement: https://github.com/ZenUml/core/issues/406
       Set text color to text-skin-base for all messages and allow fragments to override it. -->
  <component
    class="text-left text-sm text-skin-message"
    :origin="origin"
    :class="{ hidden: collapsedCheck }"
    v-bind:is="subStatement"
    :context="context"
    :comment="comment"
    :commentObj="commentObj"
    :number="number"
  ></component>
</template>

<script>
import Creation from "./Creation/Creation.vue";
import Interaction from "./Interaction/Interaction.vue";
import InteractionAsync from "./InteractionAsync/Interaction-async.vue";
import FragmentAlt from "./Fragment/FragmentAlt.vue";
import FragmentPar from "./Fragment/FragmentPar.vue";
import FragmentLoop from "./Fragment/FragmentLoop.vue";
import FragmentOpt from "./Fragment/FragmentOpt.vue";
import FragmentSection from "./Fragment/FragmentSection.vue";
import FragmentCritical from "./Fragment/FragmentCritical.vue";
import FragmentRef from "./Fragment/FragmentRef.vue";
import FragmentTryCatchFinally from "./Fragment/FragmentTryCatchFinally.vue";
import Return from "./Return/Return.vue";
import Divider from "./Divider/Divider.vue";
import Comment from "../../../../../Comment/Comment";

export default {
  name: "statement",
  props: ["origin", "context", "number", "collapsed"],
  computed: {
    comment: function () {
      return this.context.getComment() ? this.context.getComment() : "";
    },
    commentObj: function () {
      return new Comment(this.comment);
    },
    subStatement: function () {
      // eslint-disable-next-line @typescript-eslint/no-this-alias
      let that = this;
      let dict = {
        loop: "FragmentLoop",
        alt: "FragmentAlt",
        par: "FragmentPar",
        opt: "FragmentOpt",
        section: "FragmentSection",
        critical: "FragmentCritical",
        tcf: "FragmentTryCatchFinally",
        ref: "FragmentRef",
        creation: "Creation",
        message: "Interaction",
        asyncMessage: "InteractionAsync",
        divider: "Divider",
        ret: "Return",
      };
      let key = Object.keys(dict).find((x) => that.context[x]() !== null);
      return dict[key];
    },
    collapsedCheck: function () {
      return this.collapsed && this.subStatement !== "Return";
    },
  },
  components: {
    Creation,
    Interaction,
    InteractionAsync,
    FragmentAlt,
    FragmentPar,
    FragmentOpt,
    FragmentSection,
    FragmentCritical,
    FragmentRef,
    FragmentTryCatchFinally,
    FragmentLoop,
    Divider,
    Return,
  },
};
</script>
