// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/SelfInvocation/SelfInvocation.vue
<template>
  <!-- style border-width means not to be overridden. -->
  <div
    class="self-invocation message self flex items-start flex-col"
    style="border-width: 0"
    @click="onClick"
    ref="messageRef"
  >
    <label
      class="name text-left group px-px hover:text-skin-message-hover hover:bg-skin-message-hover relative min-h-[1em] w-full"
    >
      <Numbering :number="number" />
      <div class="label">
        <span v-if="assignee">
          <span class="assignee px-1">{{ assignee }}</span>
          <span>=</span>
        </span>
        <MessageLabel
          :style="textStyle"
          :class="classNames"
          :labelText="signature"
          :labelPosition="labelPosition"
          :isSelf="true"
        />
      </div>
    </label>
    <svg class="arrow text-skin-message-arrow" width="30" height="24">
      <polyline
        class="line stroke-current fill-none stroke-2"
        points="0,2 28,2 28,15 14,15"
      ></polyline>
      <polyline
        class="head stroke-current fill-current stroke-2"
        points="18,9 8,15 18,21"
      ></polyline>
    </svg>
  </div>
</template>

<script setup lang="ts">
import { useStore } from "vuex";
import { ComputedRef, computed, ref, toRefs } from "vue";
import MessageLabel from "../../../../MessageLabel.vue";
import Numbering from "../../../../Numbering.vue";

const props = defineProps<{
  context?: any;
  number?: string;
  textStyle?: Record<string, string | number>;
  classNames?: any;
}>();
const { context } = toRefs(props);
const store = useStore();

const messageRef = ref();
const labelPosition: ComputedRef<[number, number]> = computed(() => {
  // do not use .signature(). Multiple signatures are allowed, e.g. method().method1().method2()
  const func = context?.value.messageBody().func();
  if (!func) return [-1, -1];
  return [func.start.start, func.stop.stop];
});

const assignee = computed(() => {
  let assignment = context?.value.Assignment();
  if (!assignment) return "";
  return assignment.getText();
});
const signature = computed(() => {
  return context?.value.SignatureText();
});
const onClick = () => {
  store.getters.onMessageClick(context, messageRef.value);
};
</script>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/SelfInvocation/SelfInvocation.tsx
import { onMessageClickAtom } from "@/store/Store";
import { useAtomValue } from "jotai";
import { CSSProperties, useMemo, useRef } from "react";
import { Numbering } from "../../../../Numbering";
import { MessageLabel } from "../../../../MessageLabel";
import { ArrowHead } from "../../Message/ArrowHead";

export const SelfInvocation = (props: {
  context?: any;
  number?: string;
  textStyle?: CSSProperties;
  classNames?: any;
}) => {
  const messageRef = useRef(null);
  const onMessageClick = useAtomValue(onMessageClickAtom);

  const assignee = props.context?.Assignment()?.getText() || "";
  const labelPosition: [number, number] = useMemo(() => {
    const func = props.context?.messageBody().func();
    if (!func) return [-1, -1];
    return [func.start.start, func.stop.stop];
  }, [props.context]);

  const onClick = () => {
    onMessageClick(props.context, messageRef.current!);
  };

  return (
    <div
      ref={messageRef}
      className="self-invocation message leading-none self flex items-start flex-col border-none"
      onClick={onClick}
    >
      <label className="name text-left group px-px relative min-h-[1em] w-full">
        <Numbering number={props.number} />
        <div className="label">
          {assignee && (
            <span>
              <span className="assignee px-1">{assignee}</span>
              <span>=</span>
            </span>
          )}
          <MessageLabel
            style={props.textStyle}
            className={props.classNames}
            labelText={props.context?.SignatureText()}
            labelPosition={labelPosition}
            isSelf={true}
          />
        </div>
      </label>
      <svg className="arrow text-skin-message-arrow" width="30" height="24">
        <polyline
          className="line stroke-current fill-none stroke-2"
          stroke="currentColor"
          fill="none"
          strokeWidth="2"
          points="0,2 28,2 28,15 14,15"
        ></polyline>
        <ArrowHead x={7} y={10} fill={true} rtl={true} className="head stroke-2" />
      </svg>
    </div>
  );
};
