// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/Occurrence/Occurrence.tsx
import { CollapseButton } from "./CollapseButton";
import { EventBus } from "@/EventBus";
import { useEffect, useMemo, useState } from "react";
import { cn } from "@/utils";
import { Block } from "../../../Block";
import { centerOf } from "../../utils";
import { useAtomValue } from "jotai";
import { coordinatesAtom } from "@/store/Store";
import { Message } from "../../Message/Message";
import { syncMessageNormalizer } from "@/utils/messageNormalizers";
import { CSSProperties } from "react";

export const Occurrence = (props: {
  context: any;
  participant: any;
  rtl?: boolean;
  number?: string;
  className?: string;
  textStyle?: CSSProperties;
  messageClassNames?: string[];
  isSelf?: boolean;
  interactionWidth?: number;
}) => {
  const coordinates = useAtomValue(coordinatesAtom);
  const [collapsed, setCollapsed] = useState(false);

  const debug = localStorage.getItem("zenumlDebug");

  const computedCenter = () => {
    try {
      return centerOf(coordinates, props.participant);
    } catch (e) {
      console.error(e);
      return 0;
    }
  };
  const hasAnyStatementsExceptReturn = () => {
    const braceBlock = props.context.braceBlock();
    if (!braceBlock) return false;
    const stats = braceBlock.block()?.stat() || [];
    const len = stats.length;
    if (len > 1) return true;
    //when the only one statement is not the RetContext
    return len === 1 && stats[0]["ret"]() == null;
  };
  const toggle = () => {
    setCollapsed(!collapsed);

    //update participant top in this cases: has child and sibling creation statement
    //e.g. : a.call() { b = new B(); b.call() { c = new C() c.call(){return}}}
    EventBus.emit("participant_set_top");
  };

  useEffect(() => {
    setCollapsed(false);
  }, [props.context]);

  const assigneeData = useMemo(() => {
    // Check if context has Assignment function (works for both CreationContext and MessageContext)
    if (typeof props.context?.Assignment !== 'function') {
      return null;
    }
    
    const assignment = props.context.Assignment();
    if (!assignment) return null;
    const content = assignment.getText() || "";
    if (!content) return null;
    return { content, labelPosition: assignment.labelPosition };
  }, [props.context]);

  const statementNumber = props.number ? `${props.number}.${props.context?.Statements()?.length + 1}` : undefined;

  return (
    <div
      className={cn(
        "occurrence min-h-6 shadow-occurrence border-skin-occurrence bg-skin-occurrence rounded-sm border-2 relative left-full w-[15px] mt-[-2px] pl-[6px]",
        { "right-to-left left-[-14px]": props.rtl },
        props.className,
      )}
      data-el-type="occurrence"
      data-belongs-to={props.participant}
      data-x-offset={0}
      data-debug-center-of={computedCenter()}
    >
      {debug && (
        <>
          <div className="absolute w-full left-0 bg-amber-700 h-3 -top-1 flex justify-center items-center">
            <div className="w-px h-full bg-black"></div>
          </div>
          <div className="absolute w-full left-0 bg-amber-700 h-3 -bottom-1 flex justify-center items-center">
            <div className="w-px h-full bg-black"></div>
          </div>
        </>
      )}
      {hasAnyStatementsExceptReturn() && (
        <CollapseButton collapsed={collapsed} onClick={toggle} />
      )}
      {props.context.braceBlock() && (
        <Block
          origin={props.participant}
          context={props.context.braceBlock().block()}
          number={props.number}
          collapsed={collapsed}
        ></Block>
      )}
      {/* Render return statement for non-self sync message and creation */}
      {assigneeData && !props.isSelf && (
        <div className={cn("statement-container my-4")}>
          <div className={cn("interaction return relative right-to-left text-left text-sm text-skin-message")}>
            <Message
              className={cn(
                "return transform -translate-y-full pointer-events-auto",
                props.messageClassNames,
              )}
              context={props.context}
              labelPosition={assigneeData.labelPosition}
              content={assigneeData.content}
              rtl={!props.rtl}
              type="return"
              number={statementNumber}
              textStyle={props.textStyle}
              style={
                props.interactionWidth !== undefined
                  ? { width: `${props.interactionWidth}px`, transform: props.rtl ? `translateX(7px)` : `translateX(calc(-100% - 7px))` }
                  : undefined
              }
              normalizeText={syncMessageNormalizer}
            />
          </div>
        </div>
      )}
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Interaction/Occurrence/Occurrence.vue
<template>
  <div
    class="occurrence shadow-occurrence border-skin-occurrence bg-skin-occurrence rounded-sm border-2 relative left-full"
    :class="{ 'right-to-left': rtl }"
    data-el-type="occurrence"
    :data-belongs-to="participant"
    :data-x-offset="center"
    :data-debug-center-of="computedCenter"
  >
    <div
      v-if="debug"
      class="absolute w-full left-0 bg-amber-700 h-3 -top-1 flex justify-center items-center"
    >
      <div class="w-px h-full bg-black"></div>
    </div>
    <div
      v-if="debug"
      class="absolute w-full left-0 bg-amber-700 h-3 -bottom-1 flex justify-center items-center"
    >
      <div class="w-px h-full bg-black"></div>
    </div>
    <collapse-button
      v-if="hasAnyStatementsExceptReturn"
      :collapsed="collapsed"
      @click="this.toggle"
    />
    <block
      :origin="participant"
      v-if="this.context.braceBlock()"
      :context="context.braceBlock().block()"
      :selfCallIndent="selfCallIndent"
      :number="number"
      :collapsed="collapsed"
      :inheritFromOccurrence="true"
    ></block>
  </div>
</template>

<script type="text/babel">
import { mapState, mapGetters } from "vuex";
import CollapseButton from "./CollapseButton.vue";
import { EventBus } from "@/EventBus";
export default {
  name: "occurrence",
  props: ["context", "selfCallIndent", "participant", "rtl", "number"],
  data: function () {
    return {
      center: 0,
      collapsed: false,
    };
  },
  computed: {
    ...mapGetters(["centerOf", "messageLayerLeft"]),
    ...mapState(["code"]),
    debug() {
      return !!localStorage.zenumlDebug;
    },
    computedCenter: function () {
      try {
        return this.centerOf(this.participant);
      } catch (e) {
        console.error(e);
        return 0;
      }
    },
    hasAnyStatementsExceptReturn: function () {
      let braceBlock = this.context.braceBlock();
      if (!braceBlock) return false;
      let stats = braceBlock.block()?.stat() || [];
      let len = stats.length;
      if (len > 1) return true;
      //when the only one statement is not the RetContext
      if (len == 1 && stats[0]["ret"]() == null) return true;
      return false;
    },
  },
  // The following code will cause the Block to be created and mounted AFTER the occurrence (and upto DiagramFrame) is updated.
  // Block must be defined globally to ensure that it is rendered in the same time cycle as the whole diagram.
  // components: {
  //   Block: () => import('../../../Block.vue')
  // },
  methods: {
    toggle() {
      this.collapsed = !this.collapsed;

      //update participant top in this cases: has child and sibling creation statement
      //e.g. : a.call() { b = new B(); b.call() { c = new C() c.call(){return}}}
      EventBus.$emit("participant_set_top");
    },
  },
  components: { CollapseButton },
  watch: {
    context() {
      if (this.collapsed) {
        this.collapsed = false;
      }
    },
  },
};
</script>

<style scoped>
.occurrence {
  width: 15px;
  /* 6 = (OccurrenceWidth(15)+1)/2 - OccurrenceBorderWidth(2)*/
  padding: 16px 0 16px 6px;
}

:deep(> .statement-container:last-child > .interaction.return:last-of-type) {
  margin-bottom: 0;
  border-bottom: 0;
  transform: translateY(1px);
}

:deep(
    > .statement-container:last-child
      > .interaction.return:last-of-type
      > .message
  ) {
  bottom: -17px;
  /* Move the absolutely positioned return message to the bottom. -17 to offset the padding of Occurrence. */
  /* height: 0; */
}

.right-to-left.occurrence {
  left: -14px;
}
</style>

<style>
.occurrence {
  margin-top: -2px;
  /* To offset Message's border-bottom width */
}
</style>
