// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Comment/Comment.tsx
import { marked } from "marked";
import DOMPurify from "dompurify";

import highlightjs from "highlight.js";

// Languages import
import plaintext from "highlight.js/lib/languages/plaintext";
import javascript from "highlight.js/lib/languages/javascript";
import bash from "highlight.js/lib/languages/bash";
import yaml from "highlight.js/lib/languages/yaml";
import CommentClass from "@/components/Comment/Comment";
import { cn } from "@/utils";

// Register languages
highlightjs.registerLanguage("plaintext", plaintext);
highlightjs.registerLanguage("javascript", javascript);
highlightjs.registerLanguage("bash", bash);
highlightjs.registerLanguage("yaml", yaml);

// Override function
const renderer = {
  codespan(code: string) {
    const endpointPattern =
      /(GET|HEAD|POST|PUT|DELETE|CONNECT|OPTIONS|TRACE|PATCH)\s+(.+)/gi;
    // let found = code.match(endpointPattern)
    const found = endpointPattern.exec(code);
    if (found?.length === 3) {
      return `
          <code class="rest-api">
          <span class="http-method-${found[1].toLowerCase()}">${found[1]}</span>
          <span class="http-path">${found[2]}</span>
          </code>
        `;
    }
    return `<code>${code}</code>`;
  },
};

marked.setOptions({
  highlight: function (code, language) {
    if (!language) {
      return highlightjs.highlightAuto(code).value;
    }
    const validLanguage = highlightjs.getLanguage(language)
      ? language
      : "plaintext";
    return highlightjs.highlight(validLanguage, code).value;
  },
  breaks: true,
});

marked.use({ renderer });

export const Comment = (props: {
  comment?: any;
  commentObj?: CommentClass;
  className?: string;
}) => {
  const markedComment = DOMPurify.sanitize(
    (props.commentObj?.text && marked.parse(props.commentObj?.text)) ||
      (props.comment && marked.parse(props.comment)),
  );

  return (
    <div
      className={cn(
        "comments text-skin-comment min-w-[100px] flex text-left opacity-50 hover:opacity-100",
        props.className,
      )}
    >
      <div
        dangerouslySetInnerHTML={{ __html: markedComment }}
        className={cn(props.commentObj?.commentClassNames)}
        style={props.commentObj?.commentStyle}
      ></div>
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Comment/Comment.vue
<template>
  <div
    class="comments text-skin-comment min-w-[100px] flex text-left opacity-50 hover:opacity-100"
  >
    <div v-html="markedComment" :class="classNames" :style="commentStyle"></div>
  </div>
</template>

<script type="text/babel">
import { marked } from "marked";
import DOMPurify from "dompurify";

import highlightjs from "highlight.js/lib/core";

// Languages import
import plaintext from "highlight.js/lib/languages/plaintext";
import javascript from "highlight.js/lib/languages/javascript";
import bash from "highlight.js/lib/languages/bash";
import yaml from "highlight.js/lib/languages/yaml";

// Register languages
highlightjs.registerLanguage("plaintext", plaintext);
highlightjs.registerLanguage("javascript", javascript);
highlightjs.registerLanguage("bash", bash);
highlightjs.registerLanguage("yaml", yaml);

// Override function
const renderer = {
  codespan(code) {
    const endpointPattern =
      /(GET|HEAD|POST|PUT|DELETE|CONNECT|OPTIONS|TRACE|PATCH)\s+(.+)/gi;
    // let found = code.match(endpointPattern)
    let found = endpointPattern.exec(code);
    if (found?.length === 3) {
      return `
          <code class="rest-api">
          <span class="http-method-${found[1].toLowerCase()}">${found[1]}</span>
          <span class="http-path">${found[2]}</span>
          </code>
        `;
    }
    return `<code>${code}</code>`;
  },
};

marked.setOptions({
  highlight: function (code, language) {
    if (!language) {
      return highlightjs.highlightAuto(code).value;
    }
    const validLanguage = highlightjs.getLanguage(language)
      ? language
      : "plaintext";
    return highlightjs.highlight(validLanguage, code).value;
  },
  breaks: true,
});

marked.use({ renderer });

export default {
  name: "comment",
  props: ["comment", "commentObj"],
  computed: {
    markedComment() {
      const dirtyHTML =
        (this.commentObj?.text && marked.parse(this.commentObj?.text)) ||
        (this.comment && marked.parse(this.comment));
      return DOMPurify.sanitize(dirtyHTML);
    },
    commentStyle() {
      return this.commentObj?.commentStyle;
    },
    classNames() {
      return this.commentObj?.commentClassNames;
    },
  },
};
</script>

<style scoped>
p {
  margin: 0;
  line-height: 1.25em;
}
</style>
