// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Block.vue
<template>
  <div class="block" :data-origin="origin">
    <div
      class="statement-container mt-1"
      :data-origin="origin"
      v-for="(stat, index) in statements"
      :key="index"
    >
      <Statement
        :origin="origin"
        :context="stat"
        :collapsed="collapsed"
        :number="getNumber(index)"
      />
    </div>
  </div>
</template>

<script lang="ts" setup>
import { computed } from "vue";
import Statement from "./Statement/Statement.vue";
import { increaseNumber } from "@/utils/Numbering";

const props = defineProps<{
  origin?: string;
  context?: any;
  number?: string;
  incremental?: boolean;
  collapsed?: boolean;
}>();
const statements = computed(() => props.context?.stat() || []);
const getNumber = (index: number) => {
  if (props.number) {
    return props.incremental
      ? increaseNumber(props.number, index)
      : `${props.number}.${index + 1}`;
  }
  return String(index + 1);
};
</script>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Block.tsx
import { increaseNumber } from "@/utils/Numbering";
import { Statement } from "./Statement/Statement";
import { cn } from "@/utils";
import { createStatementKey } from "@/positioning/vertical/StatementIdentifier";

export const Block = (props: {
  origin?: string;
  context?: any;
  number?: string;
  incremental?: boolean;
  collapsed?: boolean;
  style?: React.CSSProperties;
  className?: string;
}) => {
  const statements: any[] = props.context?.stat() || [];
  const getNumber = (index: number) => {
    if (props.number) {
      return props.incremental
        ? increaseNumber(props.number, index)
        : `${props.number}.${index + 1}`;
    }
    return String(index + 1);
  };
  return (
    <div
      className={cn("block", props.className)}
      style={props.style}
      data-origin={props.origin}
    >
      {statements.map((stat, index) => (
        <div
          className={cn(
            "statement-container my-4",
            index === statements.length - 1 &&
              "[&>.return]:-mb-4 [&>.return]:bottom-[-1px]",
          )}
          data-origin={props.origin}
          data-statement-key={createStatementKey(stat)}
          key={index}
        >
          <Statement
            origin={props.origin || ""}
            context={stat}
            collapsed={Boolean(props.collapsed)}
            number={getNumber(index)}
          />
        </div>
      ))}
    </div>
  );
};
