// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Creation/Creation.tsx
import { cn } from "@/utils";
import { Message } from "../Message";
import { Occurrence } from "../Interaction/Occurrence/Occurrence";
import { Participant } from "@/components/DiagramFrame/SeqDiagram/LifeLineLayer/Participant";
import { CodeRange } from "@/parser/CodeRange";
import {
  LIFELINE_WIDTH,
  OCCURRENCE_BAR_SIDE_WIDTH,
} from "@/positioning/Constants";
import CommentClass from "@/components/Comment/Comment";
import { useAtomValue } from "jotai";
import { cursorAtom, onElementClickAtom } from "@/store/Store";
import { Comment } from "../Comment/Comment";
import { useEffect, useMemo, useRef } from "react";
import { useArrow } from "../useArrow";

export const Creation = (props: {
  context: any;
  origin: any;
  comment?: string;
  commentObj?: CommentClass;
  number?: string;
  className?: string;
}) => {
  const messageContainerRef = useRef<HTMLDivElement>(null);
  const participantPlaceHolder = useRef<HTMLDivElement>(null);
  const cursor = useAtomValue(cursorAtom);
  const onElementClick = useAtomValue(onElementClickAtom);
  const creation = props.context?.creation();
  const target = creation?.Owner();
  const isCurrent = creation?.isCurrent(cursor);

  const { translateX, interactionWidth, rightToLeft } = useArrow({
    context: props.context,
    origin: props.origin,
    source: props.origin,
    target: creation?.Owner(),
  });

  const messageTextStyle = props.commentObj?.messageStyle;
  const messageClassNames = props.commentObj?.messageClassNames;

  const assignee = useMemo(() => {
    function safeCodeGetter(context: any) {
      return (context && context.getFormattedText()) || "";
    }
    const assignment = creation?.creationBody().assignment();
    if (!assignment) return "";
    const assignee = safeCodeGetter(assignment.assignee());
    const type = safeCodeGetter(assignment.type());
    return assignee + (type ? ":" + type : "");
  }, [creation]);

  useEffect(() => {
    if (!participantPlaceHolder.current || !messageContainerRef.current) return;
    const halfWidthOfPlaceholder =
      participantPlaceHolder.current.offsetWidth / 2;
    // 100% width does not consider of the borders.
    messageContainerRef.current.style.width = `calc(100% + ${
      halfWidthOfPlaceholder + OCCURRENCE_BAR_SIDE_WIDTH
    }px)`;
    if (rightToLeft) {
      messageContainerRef.current.style.transform = `translateX( ${-(
        halfWidthOfPlaceholder +
        OCCURRENCE_BAR_SIDE_WIDTH +
        LIFELINE_WIDTH
      )}px`;
    }
  });

  return (
    <div
      data-origin={props.origin}
      className={cn(
        "interaction creation sync text-center transform",
        {
          "right-to-left": rightToLeft,
          "-translate-x-full-minus-1": rightToLeft,
          highlight: isCurrent,
        },
        props.className,
      )}
      onClick={() => onElementClick(CodeRange.from(props.context))}
      data-signature={creation?.SignatureText()}
      style={{
        transform: "translateX(" + translateX + "px)",
        width: interactionWidth + "px",
      }}
    >
      {props.comment && <Comment commentObj={props.commentObj} />}
      <div
        ref={messageContainerRef}
        data-type="creation"
        className={cn(
          "message-container pointer-events-none flex items-center h-10 relative",
          { "flex-row-reverse": rightToLeft },
        )}
        data-to={target}
      >
        <Message
          className={cn(
            "invocation w-full transform -translate-y-1/2 pointer-events-auto",
            messageClassNames,
          )}
          context={creation}
          content={creation?.SignatureText()}
          rtl={rightToLeft}
          type="creation"
          number={props.number}
          textStyle={messageTextStyle}
        />
        <div
          ref={participantPlaceHolder}
          className="invisible right-0 flex flex-col justify-center flex-shrink-0"
        >
          <Participant entity={{ name: target }} />
        </div>
      </div>
      <Occurrence
        context={creation}
        className="pointer-events-auto"
        participant={target}
        number={props.number}
      />
      {assignee && (
        <Message
          className={cn(
            "return transform -translate-y-full pointer-events-auto",
            messageClassNames,
          )}
          textStyle={messageTextStyle}
          context={creation.creationBody().assignment()}
          content={assignee}
          rtl={!rightToLeft}
          type="return"
          number={`${props.number}.${creation.Statements().length + 1}`}
        />
      )}
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Creation/Creation.vue
<template>
  <!-- .point-events-none allows hover over the participant underneath (from lifeline layer)
       .point-events-auto allows hover over the messages (from message layer, default behaviour) -->
  <div
    :data-origin="origin"
    class="interaction creation sync text-center transform"
    v-on:click.stop="onClick"
    :data-signature="signature"
    :class="{
      'right-to-left': rightToLeft,
      '-translate-x-full-minus-1': rightToLeft,
      highlight: isCurrent,
    }"
    :style="{
      transform: 'translateX(' + translateX + 'px)',

      width: interactionWidth + 'px',
    }"
  >
    <comment v-if="comment" :commentObj="commentObj" />
    <!-- flex items-center is an idiom that vertically align items left and right.
     h-10 fixes the height as the same as participant boxes.-->
    <div
      ref="messageContainer"
      data-type="creation"
      class="message-container pointer-events-none flex items-center h-10 relative"
      :class="{ 'flex-row-reverse': rightToLeft }"
      :data-to="target"
    >
      <message
        ref="messageEl"
        class="invocation w-full transform -translate-y-1/2 pointer-events-auto"
        :context="creation"
        :content="signature"
        :rtl="rightToLeft"
        type="creation"
        :number="number"
        :classNames="messageClassNames"
        :textStyle="messageTextStyle"
      />
      <div
        ref="participantPlaceHolder"
        class="invisible right-0 flex flex-col justify-center flex-shrink-0"
      >
        <participant :entity="{ name: target }" />
      </div>
    </div>
    <occurrence
      :context="creation"
      class="pointer-events-auto"
      :participant="target"
      :number="number"
    />
    <message
      class="return transform -translate-y-full pointer-events-auto"
      v-if="assignee"
      :context="creation.creationBody().assignment()"
      :content="assignee"
      :rtl="!rightToLeft"
      type="return"
      :number="`${number}.${creation.Statements().length + 1}`"
      :classNames="messageClassNames"
      :textStyle="messageTextStyle"
    />
  </div>
</template>

<script type="text/babel">
import { mapGetters, mapState } from "vuex";
import Comment from "../Comment/Comment.vue";
import Message from "../Message/Message.vue";
import Occurrence from "../Interaction/Occurrence/Occurrence.vue";
import { CodeRange } from "@/parser/CodeRange";
import Participant from "../../../../../../../components/DiagramFrame/SeqDiagram/LifeLineLayer/Participant.vue";
import ArrowMixin from "@/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/ArrowMixin";
import {
  LIFELINE_WIDTH,
  OCCURRENCE_BAR_SIDE_WIDTH,
} from "@/positioning/Constants";
import { DirectionMixin } from "@/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/DirectionMixin";

export default {
  name: "creation",
  props: ["context", "comment", "commentObj", "number"],
  mixins: [ArrowMixin, DirectionMixin],
  computed: {
    ...mapGetters(["cursor", "onElementClick", "distance2", "centerOf"]),
    ...mapState(["numbering"]),
    source() {
      return this.origin;
    },
    target() {
      return this.creation?.Owner();
    },
    creation() {
      return this.context?.creation();
    },
    signature() {
      return this.creation?.SignatureText();
    },
    assignee() {
      function safeCodeGetter(context) {
        return (context && context.getFormattedText()) || "";
      }
      let assignment = this.creation?.creationBody().assignment();
      if (!assignment) return "";
      let assignee = safeCodeGetter(assignment.assignee());
      const type = safeCodeGetter(assignment.type());
      return assignee + (type ? ":" + type : "");
    },
    isCurrent() {
      return this.creation?.isCurrent(this.cursor);
    },
    messageTextStyle() {
      return this.commentObj?.messageStyle;
    },
    messageClassNames() {
      return this.commentObj?.messageClassNames;
    },
  },
  mounted() {
    this.layoutMessageContainer();
  },
  updated() {
    this.layoutMessageContainer();
  },
  methods: {
    layoutMessageContainer() {
      let _layoutMessageContainer = () => {
        if (!this.$refs.participantPlaceHolder || !this.$refs.messageContainer)
          return;
        const halfWidthOfPlaceholder =
          this.$refs["participantPlaceHolder"].offsetWidth / 2;
        // 100% width does not consider of the borders.
        this.$refs["messageContainer"].style.width = `calc(100% + ${
          halfWidthOfPlaceholder + OCCURRENCE_BAR_SIDE_WIDTH
        }px`;
        if (this.rightToLeft) {
          this.$refs["messageContainer"].style.transform = `translateX( ${-(
            halfWidthOfPlaceholder +
            OCCURRENCE_BAR_SIDE_WIDTH +
            LIFELINE_WIDTH
          )}px`;
        }
      };
      _layoutMessageContainer();
    },
    onClick() {
      this.onElementClick(CodeRange.from(this.context));
    },
  },
  components: {
    Participant,
    Comment,
    Occurrence,
    Message,
  },
};
</script>
<style scoped>
.-translate-x-full-minus-1 {
  transform: translateX(calc(-100% - 1px));
}
</style>
