// src/components/DiagramFrame/SeqDiagram/MessageLayer/MessageLabel.tsx
import {
  codeAtom,
  modeAtom,
  onContentChangeAtom,
  cursorAtom,
  enableCurrentElementHighlightAtom,
  enableCurrentElementScrollIntoViewAtom,
} from "@/store/Store";
import { cn } from "@/utils";
import { useAtom, useAtomValue } from "jotai";
import { formatText } from "@/utils/StringUtil";
import { useEditLabel, specialCharRegex } from "@/functions/useEditLabel";
import { RenderMode } from "@/store/Store";
import type { FocusEvent, KeyboardEvent, MouseEvent } from "react";
import { useEffect, useRef } from "react";

export const MessageLabel = (props: {
  labelText: string;
  labelPosition: [number, number];
  isAsync?: boolean;
  isSelf?: boolean;
  className?: string;
  style?: React.CSSProperties;
}) => {
  const mode = useAtomValue(modeAtom);
  const [code, setCode] = useAtom(codeAtom);
  const cursor = useAtomValue(cursorAtom);
  const onContentChange = useAtomValue(onContentChangeAtom);
  const enableCurrentElementHighlight = useAtomValue(
    enableCurrentElementHighlightAtom,
  );
  const enableCurrentElementScrollIntoView = useAtomValue(
    enableCurrentElementScrollIntoViewAtom,
  );
  const formattedLabelText = formatText(props.labelText);
  const labelRef = useRef<HTMLLabelElement>(null);

  const isCurrent =
    cursor != null &&
    cursor >= props.labelPosition[0] &&
    cursor <= props.labelPosition[1] + 1;

  useEffect(() => {
    if (
      isCurrent &&
      props.labelText &&
      labelRef.current &&
      enableCurrentElementScrollIntoView
    ) {
      labelRef.current.scrollIntoView({
        behavior: "smooth",
        block: "center",
        inline: "nearest",
      });
    }
  }, [isCurrent, props.labelText, enableCurrentElementScrollIntoView]);

  const replaceLabelText = (e: FocusEvent | KeyboardEvent | MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();

    const target = e.target;
    if (!(target instanceof HTMLElement)) return;
    let newText = target.innerText.trim() ?? "";

    // If text is empty or same as the original label text,
    // we replace it with the original label text and bail out early
    if (newText === "" || newText === props.labelText) {
      target.innerText = props.labelText;
      return;
    }

    if (newText.includes(" ")) {
      newText = newText.replace(/\s+/g, " "); // remove extra spaces
    }

    // If text has special characters or space, we wrap it with double quotes
    // *NOTE*: We don't wrap the text with  quotes if it's an async message
    if (!props.isAsync && specialCharRegex.test(newText)) {
      newText = newText.replace(/"/g, ""); // remove existing double quotes
      newText = `"${newText}"`;
      specialCharRegex.lastIndex = 0;
    }

    const [start, end] = props.labelPosition;
    if (start === -1 || end === -1) {
      console.warn("labelPosition is not set");
      return;
    }

    const newCode = code.slice(0, start) + newText + code.slice(end + 1);
    setCode(newCode);
    onContentChange(newCode);
  };
  const { editing, handleDblClick, handleBlur, handleKeydown, handleKeyup } =
    useEditLabel(replaceLabelText);

  return (
    <label
      ref={labelRef}
      title="Double click to edit"
      className={cn(
        "px-1 cursor-text right hover:text-skin-message-hover hover:bg-skin-message-hover",
        editing && "cursor-text",
        isCurrent && enableCurrentElementHighlight && "bg-blue-100",
        props.className,
      )}
      style={props.style}
      contentEditable={editing && mode === RenderMode.Dynamic}
      onDoubleClick={handleDblClick}
      onBlur={handleBlur}
      onKeyUp={handleKeyup}
      onKeyDown={handleKeydown}
    >
      {formattedLabelText}
    </label>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/MessageLabel.vue
<template>
  <label
    ref="messageLabel"
    title="Double click to edit"
    class="px-1 cursor-text right hover:text-skin-message-hover hover:bg-skin-message-hover"
    :class="{
      'cursor-text': editing,
      highlight: isCurrent && enableCurrentElementHighlight,
    }"
    :contenteditable="editing && mode === RenderMode.Dynamic"
    @dblclick="handleDblClick"
    @blur="handleBlur"
    @keyup="handleKeyup"
    @keydown="handleKeydown"
  >
    {{ fomattedLabelText }}
  </label>
</template>
<script setup lang="ts">
import { computed, toRefs, ref, watch } from "vue";
import { useStore } from "vuex";
import { RenderMode } from "@/store/Store";
import { useEditLabel, specialCharRegex } from "@/functions/useEditLabel";
import { formatText } from "@/utils/StringUtil";

const props = withDefaults(
  defineProps<{
    labelText: string;
    labelPosition: [number, number];
    isAsync?: boolean;
    isSelf?: boolean;
  }>(),
  {
    labelText: "",
    isAsync: false,
    isSelf: false,
  },
);

const { labelText, labelPosition, isAsync } = toRefs(props);
const store = useStore();
const mode = computed(() => store.state.mode);
const code = computed(() => store.getters.code);
const cursor = computed(() => store.getters.cursor);
const messageLabel = ref<HTMLElement | null>(null);
const enableCurrentElementHighlight = computed(
  () => store.state.enableCurrentElementHighlight ?? false,
);
const enableCurrentElementScrollIntoView = computed(
  () => store.state.enableCurrentElementScrollIntoView ?? false,
);

const isCurrent = computed(() => {
  if (!labelPosition.value || !cursor.value) return false;
  const cursorIndex = cursor.value;
  const [start, end] = labelPosition.value;
  var is_current = cursorIndex >= start && cursorIndex <= end + 1;
  return is_current;
});

watch([isCurrent, labelText], ([newIsCurrent, newLabelText]) => {
  if (
    newIsCurrent &&
    newLabelText &&
    messageLabel.value &&
    enableCurrentElementScrollIntoView.value
  ) {
    messageLabel.value.scrollIntoView({
      behavior: "smooth",
      block: "center",
      inline: "nearest",
    });
  }
});

const onContentChange = computed(
  () => store.getters.onContentChange || (() => {}),
);
const fomattedLabelText = computed(() => formatText(labelText.value));

function updateCode(code: string) {
  store.dispatch("updateCode", { code });
  onContentChange.value(code);
}

function replaceLabelText(e: Event) {
  e.preventDefault();
  e.stopPropagation();

  const target = e.target;
  if (!(target instanceof HTMLElement)) return;
  let newText = target.innerText.trim() ?? "";

  // If text is empty or same as the original label text,
  // we replace it with the original label text and bail out early
  if (newText === "" || newText === labelText.value) {
    target.innerText = labelText.value;
    return;
  }

  if (newText.includes(" ")) {
    newText = newText.replace(/\s+/g, " "); // remove extra spaces
  }

  // If text has special characters or space, we wrap it with double quotes
  // *NOTE*: We don't wrap the text with  quotes if it's an async message
  if (!isAsync.value && specialCharRegex.test(newText)) {
    newText = newText.replace(/"/g, ""); // remove existing double quotes
    newText = `"${newText}"`;
    specialCharRegex.lastIndex = 0;
  }

  const [start, end] = labelPosition.value;
  if (start === -1 || end === -1) {
    console.warn("labelPosition is not set");
    return;
  }

  const newCode =
    code.value.slice(0, start) + newText + code.value.slice(end + 1);
  updateCode(newCode);
}

const { editing, handleDblClick, handleBlur, handleKeydown, handleKeyup } =
  useEditLabel(replaceLabelText);
</script>
