// src/components/DiagramFrame/SeqDiagram/MessageLayer/Numbering.tsx
import { enableNumberingAtom } from "@/store/Store";
import { useAtomValue } from "jotai";

export const Numbering = (props: { number?: number | string }) => {
  const enableNumbering = useAtomValue(enableNumberingAtom);

  if (!enableNumbering) return null;
  return (
    <div className="absolute text-xs right-[100%] top-0 pr-1 group-hover:hidden text-gray-500 font-thin">
      {props.number}
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Numbering.vue
<template>
  <div
    v-if="numbering"
    class="absolute text-xs right-[100%] top-0 pr-1 group-hover:hidden text-gray-500 font-thin"
  >
    {{ number }}
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { useStore } from "vuex";

defineProps<{
  number?: number | string;
}>();

const store = useStore();
// @ts-ignore
const numbering = computed(() => store.state.numbering);
</script>
