// src/components/DiagramFrame/SeqDiagram/MessageLayer/StylePanel.vue
<template>
  <FloatVirtual
    key="tool"
    @initial="onInitial"
    placement="top"
    :offset="5"
    :flip="{ padding: flipOffset }"
    shift
    zIndex="30"
  >
    <div class="flex bg-white shadow-md z-10 rounded-md p-1">
      <div
        v-for="btn of btns"
        @click="() => onClick(btn.class)"
        :key="btn.name"
      >
        <div
          class="w-6 mx-1 py-1 rounded-md text-black text-center cursor-pointer hover:bg-gray-200"
          :class="[
            btn.class,
            { 'bg-gray-100': existingStyles.includes(btn.class) },
          ]"
        >
          {{ btn.content }}
        </div>
      </div>
    </div>
  </FloatVirtual>
</template>
<script setup lang="ts">
import {
  FloatVirtual,
  FloatVirtualInitialProps,
  useOutsideClick,
} from "@headlessui-float/vue";
import { computed, ref } from "vue";
import { getLineHead, getPrevLine, getPrevLineHead } from "@/utils/StringUtil";
import { useStore } from "vuex";
import { getElementDistanceToTop } from "@/utils/dom";
import { PARTICIPANT_HEIGHT } from "@/positioning/Constants";

const messageContext = ref<{ value: any }>({ value: null });
const store = useStore();
const onContentChange = computed(
  () => store.getters.onContentChange || (() => {}),
);
const flipOffset = computed(
  () =>
    getElementDistanceToTop(store.getters.diagramElement) + PARTICIPANT_HEIGHT,
);
const code = computed(() => store.getters.code);
const updateCode = (code: string) => {
  store.dispatch("updateCode", { code });
  onContentChange.value(code);
};
const existingStyles = ref<string[]>([]);
let onClick: (style: string) => void;

const onInitial = ({ show, reference, floating }: FloatVirtualInitialProps) => {
  let start: number;
  let lineHead: number;
  let prevLine: string;
  let leadingSpaces: string;
  let prevLineIsComment: boolean;
  let hasStyleBrackets: boolean;
  store.commit("onMessageClick", (context: any, element: HTMLElement) => {
    start = context.value.start.start;
    lineHead = getLineHead(code.value, start);
    prevLine = getPrevLine(code.value, start);
    leadingSpaces = code.value.slice(lineHead).match(/^\s*/)?.[0] || "";
    prevLineIsComment = prevLine.trim().startsWith("//");
    if (prevLineIsComment) {
      const trimedPrevLine = prevLine.trimStart().slice(2).trimStart();
      const styleStart = trimedPrevLine.indexOf("[");
      const styleEnd = trimedPrevLine.indexOf("]");
      hasStyleBrackets = Boolean(styleStart === 0 && styleEnd);
      if (hasStyleBrackets) {
        existingStyles.value = trimedPrevLine
          .slice(styleStart + 1, styleEnd)
          .split(",")
          .map((s) => s.trim());
      } else {
        existingStyles.value = [];
      }
    }
    reference.value = {
      getBoundingClientRect: () => element.getBoundingClientRect(),
    };
    messageContext.value = context;
    show.value = true;
  });
  useOutsideClick(
    floating,
    () => {
      show.value = false;
      existingStyles.value = [];
    },
    computed(() => show.value),
  );

  onClick = (style: string) => {
    show.value = false;
    if (!messageContext.value.value) return;
    if (prevLineIsComment) {
      let newComment = "";
      if (hasStyleBrackets) {
        let updatedStyles;

        if (existingStyles.value.includes(style)) {
          updatedStyles = existingStyles.value.filter((s) => s !== style);
        } else {
          updatedStyles = [...existingStyles.value, style];
        }

        newComment = `${leadingSpaces}// [${updatedStyles
          .filter(Boolean)
          .join(", ")}] ${prevLine
          .slice(prevLine.indexOf("]") + 1)
          .trimStart()}`;
      } else {
        newComment = `${leadingSpaces}// [${style}] ${prevLine
          .slice((prevLine.match(/\/\/*/)?.index || -2) + 2)
          .trimStart()}`;
      }
      if (!newComment.endsWith("\n")) newComment += "\n";
      updateCode(
        code.value.slice(0, getPrevLineHead(code.value, start)) +
          newComment +
          code.value.slice(lineHead),
      );
    } else {
      updateCode(
        code.value.slice(0, lineHead) +
          `${leadingSpaces}// [${style}]\n` +
          code.value.slice(lineHead),
      );
    }
  };
};

const btns = [
  {
    name: "bold",
    content: "B",
    class: "font-bold",
  },
  {
    name: "italic",
    content: "I",
    class: "italic",
  },
  {
    name: "underline",
    content: "U",
    class: "underline",
  },
  {
    name: "strikethrough",
    content: "S",
    class: "line-through",
  },
];
</script>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/StylePanel.tsx
import { cn } from "@/utils";
import { getLineHead, getPrevLine, getPrevLineHead } from "@/utils/StringUtil";
import { useAtom, useAtomValue, useSetAtom } from "jotai";
import {
  codeAtom,
  onContentChangeAtom,
  onMessageClickAtom,
} from "@/store/Store";
import { useEffect, useRef, useState } from "react";
import { useFloating } from "@floating-ui/react";
import { useOutsideClick } from "@/functions/useOutsideClick";
import { offsetRangeOf } from "@/parser/helpers";
import type { CodeRange } from "@/parser/CodeRange";
import { offsetFromLineCol } from "@/utils/StringUtil";

const btns = [
  {
    name: "bold",
    content: "B",
    class: "font-bold",
  },
  {
    name: "italic",
    content: "I",
    class: "italic",
  },
  {
    name: "underline",
    content: "U",
    class: "underline",
  },
  {
    name: "strikethrough",
    content: "S",
    class: "line-through",
  },
];

export const StylePanel = () => {
  const [code, setCode] = useAtom(codeAtom);
  const onContentChange = useAtomValue(onContentChangeAtom);
  const setOnMessageClick = useSetAtom(onMessageClickAtom);
  const [isOpen, setIsOpen] = useState(false);
  const [existingStyles, setExistingStyles] = useState<string[]>([]);
  const [messageContext, setMessageContext] = useState("");

  const updateCode = (newCode: string) => {
    setCode(newCode);
    onContentChange(newCode);
  };

  const messageData = useRef({
    start: 0,
    lineHead: 0,
    prevLine: "",
    leadingSpaces: "",
    prevLineIsComment: false,
    hasStyleBrackets: false,
  });

  const { refs, floatingStyles } = useFloating({
    open: isOpen,
    onOpenChange: setIsOpen,
  });

  const handleClick = (style: string) => {
    setIsOpen(false);
    if (!messageContext) return;
    const message = messageData.current;
    if (message.prevLineIsComment) {
      let newComment = "";
      if (message.hasStyleBrackets) {
        let updatedStyles;

        if (existingStyles.includes(style)) {
          updatedStyles = existingStyles.filter((s) => s !== style);
        } else {
          updatedStyles = [...existingStyles, style];
        }

        newComment = `${message.leadingSpaces}// [${updatedStyles
          .filter(Boolean)
          .join(", ")}] ${message.prevLine
          .slice(message.prevLine.indexOf("]") + 1)
          .trimStart()}`;
      } else {
        newComment = `${message.leadingSpaces}// [${style}] ${message.prevLine
          .slice((message.prevLine.match(/\/\/*/)?.index || -2) + 2)
          .trimStart()}`;
      }
      if (!newComment.endsWith("\n")) newComment += "\n";
      updateCode(
        code.slice(0, getPrevLineHead(code, message.start)) +
          newComment +
          code.slice(message.lineHead),
      );
    } else {
      updateCode(
        code.slice(0, message.lineHead) +
          `${message.leadingSpaces}// [${style}]\n` +
          code.slice(message.lineHead),
      );
    }
  };

  useOutsideClick(refs.floating.current, () => {
    setIsOpen(false);
  });

  useEffect(() => {
    setOnMessageClick((payloadOrContext: any, element: HTMLElement) => {
      // make sure this is triggered after the outsideclicking
      setTimeout(() => {
        const message = messageData.current;
        // New approach: expect startOffset or codeRange
        const hasNewPayload =
          payloadOrContext &&
          (typeof payloadOrContext.startOffset === "number" ||
            payloadOrContext.codeRange);
        let newStart: number | null = null;
        if (hasNewPayload) {
          if (typeof payloadOrContext.startOffset === "number") {
            newStart = payloadOrContext.startOffset as number;
          } else if (payloadOrContext.codeRange) {
            const cr = payloadOrContext.codeRange as CodeRange;
            try {
              newStart = offsetFromLineCol(code, cr.start.line, cr.start.col);
            } catch {}
          }
        }
        // Do not fallback. If newStart is not provided, bail out.
        if (newStart == null) {
          console.warn("[stylepanel] missing startOffset/codeRange in payload; aborting");
          return;
        }
        message.start = newStart;

        // Parity check (do not affect behavior)
        const legacyContext =
          (payloadOrContext && payloadOrContext.context) || payloadOrContext;
        const legacyRange = offsetRangeOf(legacyContext);
        const legacyStart = Array.isArray(legacyRange) ? legacyRange[0] : 0;
        if (newStart !== legacyStart) {
          console.warn("[stylepanel] start offset mismatch", {
            legacyStart,
            newStart,
          });
        } else {
          console.log("[stylepanel] start offset parity ✓", { start: newStart });
        }
        message.lineHead = getLineHead(code, message.start);
        message.prevLine = getPrevLine(code, message.start);
        message.leadingSpaces =
          code.slice(message.lineHead).match(/^\s*/)?.[0] || "";
        message.prevLineIsComment = message.prevLine.trim().startsWith("//");
        if (message.prevLineIsComment) {
          const trimedPrevLine = message.prevLine
            .trimStart()
            .slice(2)
            .trimStart();
          const styleStart = trimedPrevLine.indexOf("[");
          const styleEnd = trimedPrevLine.indexOf("]");
          message.hasStyleBrackets = Boolean(styleStart === 0 && styleEnd);
          if (message.hasStyleBrackets) {
            setExistingStyles(
              trimedPrevLine
                .slice(styleStart + 1, styleEnd)
                .split(",")
                .map((s) => s.trim()),
            );
          } else {
            setExistingStyles([]);
          }
        }
        refs.setReference(element);
        setMessageContext(legacyContext);
        setIsOpen(true);
      }, 0);
    });
  }, [code, refs, setOnMessageClick]);

  return (
    <div id="style-panel" ref={refs.setFloating} style={floatingStyles}>
      {isOpen && (
        <div className="flex bg-white shadow-md z-10 rounded-md p-1">
          {btns.map((btn) => (
            <div onClick={() => handleClick(btn.class)} key={btn.name}>
              <div
                className={cn(
                  "w-6 mx-1 py-1 rounded-md text-black text-center cursor-pointer hover:bg-gray-200",
                  [
                    btn.class,
                    { "bg-gray-100": existingStyles.includes(btn.class) },
                  ],
                )}
              >
                {btn.content}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
