// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/CollapseButton.vue
<template>
  <div class="collapsible-header">
    <label class="mb-0">{{ label }}</label>
    <Icon name="collapse-expanded"
          :icon-class="`w-4 h-4 collapse-button cursor-pointer ${!collapsed ? 'expanded' : ''}`" v-if="!collapsed"
          @icon-click="$emit('click', $event)"/>
    <Icon name="collapse-unexpanded" icon-class="w-4 h-4 cursor-pointer inline-block" v-else
          @icon-click="$emit('click', $event)"/>
  </div>
</template>

<script>
import Icon from "@/components/Icon/Icon.vue";

export default {
  components: {Icon},
  props: ['label', 'collapsed'],
  emits: ['click'],
};
</script>
<style scoped>
.collapsible-header {
  display: flex; width: 100%; justify-content: space-between;
}
.collapse-button {
  display: none;
}
.fragment:hover .collapsible-header .collapse-button.expanded {
  display: inline-block !important;
}
</style>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/CollapseButton.tsx
import Icon from "@/components/Icon/Icons";
import { cn } from "@/utils";

export const CollapseButton = (props: {
  label: string;
  collapsed?: boolean;
  onClick?: () => void;
  style?: React.CSSProperties;
  className?: string;
}) => {
  return (
    <div
      className={cn(
        "collapsible-header flex w-full justify-between",
        props.className,
      )}
      style={props.style}
    >
      <label className="mb-0">{props.label}</label>
      {props.collapsed ? (
        <Icon
          name="collapse-unexpanded"
          className="w-4 h-4 cursor-pointer"
          onClick={props.onClick}
        />
      ) : (
        <Icon
          name="collapse-expanded"
          className={cn(
            "w-4 h-4 collapse-button cursor-pointer hidden group-[.fragment]:group-hover:inline-block",
            props.collapsed && "inline-block",
          )}
          onClick={props.onClick}
        />
      )}
    </div>
  );
};
