// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentTryCatchFinally.tsx
import CommentClass from "@/components/Comment/Comment";
import { useFragmentData } from "./useFragmentData";
import { Comment } from "../Comment/Comment";
import { Numbering } from "../../../Numbering";
import { CollapseButton } from "./CollapseButton";
import { cn } from "@/utils";
import { Block } from "../../Block";
import { blockLength } from "@/utils/Numbering";
import "./FragmentTryCatchFinally.css";
import { useMemo } from "react";

export const FragmentTryCatchFinally = (props: {
  context: any;
  comment: string;
  commentObj: CommentClass;
  number: string;
  origin: string;
  className?: string;
}) => {
  const {
    collapsed,
    toggleCollapse,
    paddingLeft,
    fragmentStyle,
    border,
    leftParticipant,
  } = useFragmentData(props.context, props.origin);

  const exception = (ctx: any) => {
    return ctx?.invocation()?.parameters()?.getFormattedText();
  };
  const blockInCatchBlock = (ctx: any) => {
    return ctx?.braceBlock()?.block();
  };

  const tcf = props.context.tcf();
  const blockInTryBlock = tcf?.tryBlock()?.braceBlock()?.block();
  const finallyBlock = tcf?.finallyBlock()?.braceBlock()?.block();
  const blockLengthAcc = useMemo(() => {
    const acc = [blockLength(blockInTryBlock)];
    if (tcf?.catchBlock()) {
      tcf.catchBlock().forEach((block: any) => {
        acc.push(acc[acc.length - 1] + blockLength(blockInCatchBlock(block)));
      });
    }
    return acc;
  }, [tcf, blockInTryBlock]);

  return (
    <div className={props.className}>
      <div
        data-origin={props.origin}
        data-left-participant={leftParticipant}
        data-frame-padding-left={border.left}
        data-frame-padding-right={border.right}
        className="group fragment fragment-tcf tcf border-skin-fragment rounded"
        style={fragmentStyle}
      >
        <div className="segment">
          {props.commentObj.text && (
            <Comment comment={props.comment} commentObj={props.commentObj} />
          )}
          <div className="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative">
            <Numbering number={props.number} />
            <div className="name font-semibold p-1 border-b">
              <CollapseButton
                label="Try"
                collapsed={collapsed}
                onClick={toggleCollapse}
                style={props.commentObj.messageStyle}
                className={cn(props.commentObj.messageClassNames)}
              />
            </div>
          </div>
        </div>
        <div className={collapsed ? "hidden" : ""}>
          <div className="segment">
            {blockInTryBlock && (
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={blockInTryBlock}
                number={`${props.number}.1`}
                incremental
              />
            )}
          </div>
          {tcf.catchBlock().map((catchBlock: any, index: number) => (
            <div
              className="segment mt-2 border-t border-solid"
              key={index + 500}
            >
              <div
                className="header inline-block bg-skin-frame opacity-65"
                key={index + 1000}
              >
                <label className="keyword catch p-1">catch</label>
                <label className="exception p-1">{exception(catchBlock)}</label>
              </div>
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={blockInCatchBlock(catchBlock)}
                key={index + 2000}
                number={`${props.number}.${blockLengthAcc[index] + 1}`}
                incremental
              />
            </div>
          ))}
          {finallyBlock && (
            <div className="segment mt-2 border-t border-solid">
              <div className="header flex text-skin-fragment finally">
                <label className="keyword finally bg-skin-frame opacity-65 px-1 inline-block">
                  finally
                </label>
              </div>
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={finallyBlock}
                number={`${props.number}.${
                  blockLengthAcc[blockLengthAcc.length - 1] + 1
                }`}
                incremental
              />
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentTryCatchFinally.vue
<template>
  <div
    :data-origin="origin"
    :data-left-participant="leftParticipant"
    :data-frame-padding-left="border.left"
    :data-frame-padding-right="border.right"
    class="fragment tcf border-skin-fragment rounded"
    :style="fragmentStyle"
  >
    <div class="segment">
      <comment
        v-if="commentObj.text"
        :comment="comment"
        :commentObj="commentObj"
      />
      <div
        class="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative"
      >
        <div
          v-if="numbering"
          class="absolute right-[100%] top-0 pr-1 group-hover:hidden text-gray-500 font-thin leading-6"
        >
          {{ number }}
        </div>
        <div class="name font-semibold p-1 border-b">
          <collapse-button
            label="Try"
            :collapsed="collapsed"
            @click="this.toggle"
            :style="commentObj.messageStyle"
            :class="commentObj.messageClassNames"
          />
        </div>
      </div>
    </div>
    <div :class="{ hidden: collapsed }">
      <div class="segment">
        <!-- fragment-offset set as offsetX - 1 for fragment border     -->
        <block
          :origin="origin"
          v-if="blockInTryBlock"
          :style="{ paddingLeft: `${offsetX}px` }"
          :context="blockInTryBlock"
          :number="`${number}.1`"
          incremental
        >
        </block>
      </div>
      <template
        v-for="(catchBlock, index) in tcf.catchBlock()"
        :key="index + 500"
      >
        <div class="segment mt-2 border-t border-solid">
          <div
            class="header inline-block bg-skin-frame/[0.66]"
            :key="index + 1000"
          >
            <label class="keyword catch p-1">catch</label
            ><label class="exception p-1">{{ exception(catchBlock) }}</label>
          </div>
          <block
            :origin="origin"
            :style="{ paddingLeft: `${offsetX}px` }"
            :context="blockInCatchBlock(catchBlock)"
            :key="index + 2000"
            :number="`${number}.${blockLengthAcc[index] + 1}`"
            incremental
          ></block>
        </div>
      </template>
      <template v-if="finallyBlock">
        <div class="segment mt-2 border-t border-solid">
          <div class="header flex text-skin-fragment finally">
            <label
              class="keyword finally bg-skin-frame/[0.66] px-1 inline-block"
              >finally</label
            >
          </div>
          <block
            :origin="origin"
            :style="{ paddingLeft: `${offsetX}px` }"
            :context="finallyBlock"
            :number="`${number}.${
              blockLengthAcc[blockLengthAcc.length - 1] + 1
            }`"
            incremental
          ></block>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import { mapState } from "vuex";
import fragment from "./FragmentMixin";
import { blockLength } from "@/utils/Numbering";

export default {
  name: "fragment-tcf",
  props: ["context", "comment", "commentObj", "number"],
  mixins: [fragment],
  computed: {
    ...mapState(["numbering"]),
    from: function () {
      return this.context.Origin();
    },
    tcf: function () {
      return this.context.tcf();
    },
    blockInTryBlock: function () {
      return this.tcf?.tryBlock()?.braceBlock()?.block();
    },
    finallyBlock: function () {
      return this.tcf?.finallyBlock()?.braceBlock()?.block();
    },
    blockLengthAcc() {
      const acc = [blockLength(this.blockInTryBlock)];
      if (this.tcf?.catchBlock()) {
        this.tcf.catchBlock().forEach((block) => {
          acc.push(
            acc[acc.length - 1] + blockLength(this.blockInCatchBlock(block)),
          );
        });
      }
      return acc;
    },
  },
  methods: {
    exception(ctx) {
      return ctx?.invocation()?.parameters()?.getFormattedText();
    },
    blockInCatchBlock(ctx) {
      return ctx?.braceBlock()?.block();
    },
  },
};
</script>

<style scoped>
/* We need to do this because tailwind 3.2.4 set border-color to #e5e7eb via '*'. */
* {
  border-color: inherit;
}
</style>
