// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentPar.vue
<template>
  <div
    :data-origin="origin"
    :data-left-participant="leftParticipant"
    :data-frame-padding-left="border.left"
    :data-frame-padding-right="border.right"
    class="fragment par border-skin-fragment rounded"
    :style="fragmentStyle"
  >
    <comment
      v-if="commentObj.text"
      :comment="comment"
      :commentObj="commentObj"
    />
    <div
      class="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative"
    >
      <Numbering :number="number" />
      <div class="name font-semibold p-1 border-b">
        <collapse-button
          label="Par"
          :collapsed="collapsed"
          @click="this.toggle"
          :style="commentObj.messageStyle"
          :class="commentObj.messageClassNames"
        />
      </div>
    </div>
    <block
      v-if="!!par.braceBlock()"
      :origin="origin"
      :class="{ hidden: collapsed }"
      :style="{ paddingLeft: `${offsetX}px` }"
      :context="par.braceBlock().block()"
      :number="number"
    ></block>
  </div>
</template>

<script>
import fragment from "./FragmentMixin";
import Numbering from "../../../Numbering.vue";

export default {
  name: "fragment-par",
  props: ["context", "comment", "commentObj", "number"],
  mixins: [fragment],
  computed: {
    par: function () {
      return this.context.par();
    },
  },
  components: {
    Numbering,
  },
};
</script>
<style scoped>
/* We need to do this because tailwind 3.2.4 set border-color to #e5e7eb via '*'. */
* {
  border-color: inherit;
}
</style>
<style>
/* Knowledge: Shortcut version `border-top: 1px solid` will reset border-top-color to not specified.
   Then according to the spec, it will use text color for border-top-color.
   https://stackoverflow.com/a/8663547/529187
 */
.fragment.par > .block > .statement-container:not(:first-child) {
  border-top-color: inherit;
  border-top-width: 1px;
  border-top-style: solid;
}
</style>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentPar.tsx
import CommentClass from "@/components/Comment/Comment";
import { useFragmentData } from "./useFragmentData";
import { Comment } from "../Comment/Comment";
import { Numbering } from "../../../Numbering";
import { CollapseButton } from "./CollapseButton";
import { cn } from "@/utils";
import { Block } from "../../Block";
import "./FragmentPar.css";

export const FragmentPar = (props: {
  context: any;
  origin: string;
  comment?: string;
  commentObj?: CommentClass;
  number?: string;
  className?: string;
}) => {
  const {
    collapsed,
    toggleCollapse,
    paddingLeft,
    fragmentStyle,
    border,
    leftParticipant,
  } = useFragmentData(props.context, props.origin);

  const par = props.context.par();

  return (
    <div className={props.className}>
      <div
        data-origin={origin}
        data-left-participant={leftParticipant}
        data-frame-padding-left={border.left}
        data-frame-padding-right={border.right}
        className="group fragment fragment-par par border-skin-fragment rounded"
        style={fragmentStyle}
      >
        {props.commentObj?.text && (
          <Comment comment={props.comment} commentObj={props.commentObj} />
        )}
        <div className="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative">
          <Numbering number={props.number} />
          <div className="name font-semibold p-1 border-b">
            <CollapseButton
              label="Par"
              collapsed={collapsed}
              onClick={toggleCollapse} // Assuming 'this.toggle' is accessible or replace with appropriate handler
              style={props.commentObj?.messageStyle}
              className={cn(props.commentObj?.messageClassNames)}
            />
          </div>
        </div>
        {!!par.braceBlock() && (
          <Block
            origin={leftParticipant}
            className={cn(
              "[&>.statement-container:not(:first-child)]",
              collapsed ? "hidden" : "",
            )}
            style={{ paddingLeft: `${paddingLeft}px` }}
            context={par.braceBlock().block()}
            number={`${props.number}.1`}
            incremental
          />
        )}
      </div>
    </div>
  );
};
