// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentAlt.tsx
import CommentClass from "@/components/Comment/Comment";
import { blockLength } from "@/utils/Numbering";
import { CollapseButton } from "./CollapseButton";
import { Block } from "../../Block";
import { useFragmentData } from "./useFragmentData";
import { Comment } from "../Comment/Comment";
import { Numbering } from "../../../Numbering";
import { cn } from "@/utils";
import { ConditionLabel } from "./ConditionLabel";
import "./FragmentAlt.css";
import { Fragment, useMemo } from "react";

export const FragmentAlt = (props: {
  context: any;
  origin: string;
  comment?: string;
  commentObj?: CommentClass;
  number?: string;
  className?: string;
}) => {
  const alt = props.context.alt();
  const ifBlock = alt?.ifBlock();
  const elseIfBlocks = alt?.elseIfBlock();
  const elseBlock = alt?.elseBlock()?.braceBlock()?.block();
  const blockInIfBlock = alt?.ifBlock()?.braceBlock()?.block();
  const blockLengthAcc = useMemo(() => {
    const acc = [blockLength(blockInIfBlock)];
    if (alt?.elseIfBlock()) {
      alt.elseIfBlock().forEach((block: any) => {
        acc.push(acc[acc.length - 1] + blockLength(blockInElseIfBlock(block)));
      });
    }
    return acc;
  }, [alt, blockInIfBlock]);

  function conditionFromIfElseBlock(block: any) {
    return block?.parExpr()?.condition();
  }

  function blockInElseIfBlock(block: any) {
    return block?.braceBlock()?.block();
  }

  const {
    collapsed,
    toggleCollapse,
    paddingLeft,
    fragmentStyle,
    leftParticipant,
  } = useFragmentData(props.context, props.origin);

  return (
    <div
      data-origin={props.origin}
      data-left-participant={props.origin}
      data-frame-padding-left={props.commentObj?.messageStyle?.paddingLeft}
      data-frame-padding-right={props.commentObj?.messageStyle?.paddingRight}
      className={cn(
        "group fragment fragment-alt alt border-skin-fragment rounded",
        props.className,
      )}
      style={fragmentStyle}
    >
      <div className="segment">
        {props.commentObj?.text && (
          <Comment comment={props.comment} commentObj={props.commentObj} />
        )}
        <div className="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative">
          <Numbering number={props.number} />
          <div className="name font-semibold p-1 border-b">
            <label className="p-0">
              <CollapseButton
                label="Alt"
                collapsed={collapsed}
                onClick={toggleCollapse}
                style={props.commentObj?.messageStyle}
                className={cn(props.commentObj?.messageClassNames)}
              />
            </label>
          </div>
        </div>
      </div>

      <div className={collapsed ? "hidden" : "block"}>
        <div className="segment">
          <div className="text-skin-fragment flex">
            <ConditionLabel condition={conditionFromIfElseBlock(ifBlock)} />
          </div>
          {blockInIfBlock && (
            <Block
              origin={leftParticipant}
              style={{ paddingLeft: `${paddingLeft}px` }}
              context={blockInIfBlock}
              number={`${props.number}.1`}
              incremental
            />
          )}
        </div>
        {elseIfBlocks.map((elseIfBlock: any, index: number) => (
          <Fragment key={index}>
            <div
              className="segment mt-2 border-t border-solid"
              key={index + 500}
            >
              <div className="text-skin-fragment" key={index + 1000}>
                <label className="else-if hidden">else if</label>
                <ConditionLabel
                  condition={conditionFromIfElseBlock(elseIfBlock)}
                />
              </div>
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={blockInElseIfBlock(elseIfBlock)}
                key={index + 2000}
                number={`${props.number}.${blockLengthAcc[index] + 1}`}
                incremental
              />
            </div>
          </Fragment>
        ))}
        {elseBlock && (
          <>
            <div className="segment mt-2 border-t border-solid">
              <div className="text-skin-fragment">
                <label className="p-1">[else]</label>
              </div>
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={elseBlock}
                number={`${props.number}.${
                  blockLengthAcc[blockLengthAcc.length - 1] + 1
                }`}
                incremental
              />
            </div>
          </>
        )}
      </div>
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentAlt.vue
<template>
  <div
    :data-origin="origin1"
    :data-from="from"
    :data-left-participant="leftParticipant"
    :data-frame-padding-left="border.left"
    :data-frame-padding-right="border.right"
    class="fragment alt border-skin-fragment rounded"
    :style="fragmentStyle"
  >
    <div class="segment">
      <comment
        v-if="commentObj.text"
        :comment="comment"
        :commentObj="commentObj"
      />
      <div
        class="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative"
      >
        <div
          v-if="numbering"
          class="absolute right-[100%] top-0 pr-1 group-hover:hidden text-gray-500 font-thin leading-6"
        >
          {{ number }}
        </div>
        <div class="name font-semibold p-1 border-b">
          <label class="p-0">
            <collapse-button
              label="Alt"
              :collapsed="collapsed"
              @click="this.toggle"
              :style="commentObj.messageStyle"
              :class="commentObj.messageClassNames"
            />
          </label>
        </div>
      </div>
    </div>

    <div :class="{ hidden: collapsed }">
      <div class="segment">
        <div class="text-skin-fragment flex">
          <ConditionLabel :condition="conditionFromIfElseBlock(ifBlock)" />
        </div>
        <block
          :origin1="origin1"
          v-if="blockInIfBlock"
          :style="{ paddingLeft: `${offsetX}px` }"
          :context="blockInIfBlock"
          :selfCallIndent="selfCallIndent"
          :number="`${number}.1`"
          incremental
        ></block>
      </div>
      <template v-for="(elseIfBlock, index) in elseIfBlocks" :key="index + 500">
        <div class="segment mt-2 border-t border-solid">
          <div class="text-skin-fragment" :key="index + 1000">
            <label class="else-if hidden">else if</label>
            <ConditionLabel
              :condition="conditionFromIfElseBlock(elseIfBlock)"
            />
          </div>
          <block
            :origin1="origin1"
            :style="{ paddingLeft: `${offsetX}px` }"
            :context="blockInElseIfBlock(elseIfBlock)"
            :selfCallIndent="selfCallIndent"
            :key="index + 2000"
            :number="`${number}.${blockLengthAcc[index] + 1}`"
            incremental
          ></block>
        </div>
      </template>
      <template v-if="elseBlock">
        <div class="segment mt-2 border-t border-solid">
          <div class="text-skin-fragment">
            <label class="p-1">[else]</label>
          </div>
          <block
            :origin1="origin1"
            :style="{ paddingLeft: `${offsetX}px` }"
            :context="elseBlock"
            :selfCallIndent="selfCallIndent"
            :number="`${number}.${
              blockLengthAcc[blockLengthAcc.length - 1] + 1
            }`"
            incremental
          ></block>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import { computed } from "vue";
import { useStore } from "vuex";
import fragment from "./FragmentMixin";
import { increaseNumber, blockLength } from "@/utils/Numbering";
import ConditionLabel from "./ConditionLabel.vue";

export default {
  name: "fragment-alt",
  props: ["context", "comment", "selfCallIndent", "commentObj", "number"],
  mixins: [fragment],
  components: {
    ConditionLabel,
  },
  setup(props) {
    const store = useStore();
    const numbering = computed(() => store.state.numbering);
    const from = computed(() => props.origin1);
    const alt = computed(() => props.context.alt());
    const ifBlock = computed(() => alt.value?.ifBlock());
    const elseIfBlocks = computed(() => alt.value?.elseIfBlock());
    const elseBlock = computed(() =>
      alt.value?.elseBlock()?.braceBlock()?.block(),
    );
    const blockInIfBlock = computed(() =>
      alt.value?.ifBlock()?.braceBlock()?.block(),
    );
    const blockLengthAcc = computed(() => {
      const acc = [blockLength(blockInIfBlock.value)];
      if (alt.value?.elseIfBlock()) {
        alt.value.elseIfBlock().forEach((block) => {
          acc.push(
            acc[acc.length - 1] + blockLength(blockInElseIfBlock(block)),
          );
        });
      }
      return acc;
    });

    function conditionFromIfElseBlock(block) {
      return block?.parExpr()?.condition();
    }

    function blockInElseIfBlock(block) {
      return block?.braceBlock()?.block();
    }

    return {
      numbering,
      from,
      alt,
      blockInIfBlock,
      ifBlock,
      elseIfBlocks,
      elseBlock,
      blockLengthAcc,
      conditionFromIfElseBlock,
      blockInElseIfBlock,
      increaseNumber,
      blockLength,
    };
  },
};
</script>

<style scoped>
/* We need to do this because tailwind 3.2.4 set border-color to #e5e7eb via '*'. */
* {
  border-color: inherit;
}
</style>
