// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentSection.vue
<template>
  <div
    class="fragment section border-skin-fragment rounded"
    :style="fragmentStyle"
    :data-frame-padding-left="border.left"
    :data-frame-padding-right="border.right"
    :data-left-participant="leftParticipant"
  >
    <div class="segment">
      <comment
        v-if="commentObj.text"
        :comment="comment"
        :commentObj="commentObj"
      />
      <div
        class="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative"
      >
        <div
          v-if="numbering"
          class="absolute right-[100%] top-0 pr-1 group-hover:hidden text-gray-500 font-thin leading-6"
        >
          {{ number }}
        </div>
        <div class="name font-semibold p-1 border-b">
          <label class="p-0">
            <collapse-button
              :label="label"
              :collapsed="collapsed"
              @click="this.toggle"
              :style="commentObj.messageStyle"
              :class="commentObj.messageClassNames"
            />
          </label>
        </div>
      </div>
    </div>

    <div :class="{ hidden: collapsed }">
      <div class="segment">
        <div class="text-skin-fragment flex">
          <!-- Value -->
        </div>
        <block
          :origin="origin"
          v-if="blockInSection"
          :style="{ paddingLeft: `${offsetX}px` }"
          :context="blockInSection"
          :number="number"
        ></block>
      </div>
    </div>
  </div>
</template>

<script>
import { computed } from "vue";
import { useStore } from "vuex";
import fragment from "./FragmentMixin";
import capitalize from "lodash/capitalize";

export default {
  name: "fragment-section",
  props: ["context", "comment", "commentObj", "number"],
  mixins: [fragment],
  setup(props) {
    const store = useStore();
    const numbering = computed(() => store.state.numbering);
    const from = computed(() => props.context.Origin());
    const section = computed(() => props.context.section());
    const braceBlock = computed(() => section.value?.braceBlock());
    const atom = computed(() => section.value?.atom()?.getFormattedText());
    const blockInSection = computed(() => braceBlock.value?.block());

    const label = computed(
      () => atom.value ?? capitalize(section.value.SECTION()),
    );

    return {
      numbering,
      from,
      label,
      braceBlock,
      blockInSection,
    };
  },
};
</script>

<style scoped>
/* We need to do this because tailwind 3.2.4 set border-color to #e5e7eb via '*'. */
* {
  border-color: inherit;
}
</style>

// src/components/DiagramFrame/SeqDiagram/MessageLayer/Block/Statement/Fragment/FragmentSection.tsx
import CommentClass from "@/components/Comment/Comment";
import { useFragmentData } from "./useFragmentData";
import { Comment } from "../Comment/Comment";
import { Numbering } from "../../../Numbering";
import { CollapseButton } from "./CollapseButton";
import { Block } from "../../Block";
import { capitalize } from "radash";
import { cn } from "@/utils";
import "./FragmentSection.css";

export const FragmentSection = (props: {
  context: any;
  comment: string;
  commentObj: CommentClass;
  number: string;
  origin: string;
  className?: string;
}) => {
  const {
    collapsed,
    toggleCollapse,
    paddingLeft,
    fragmentStyle,
    border,
    leftParticipant,
  } = useFragmentData(props.context, props.origin);
  const section = props.context.section();
  const braceBlock = section?.braceBlock();
  const atom = section?.atom()?.getFormattedText();
  const blockInSection = braceBlock?.block();

  const label = atom ?? capitalize("section");

  return (
    <div className={props.className}>
      <div
        data-origin={origin}
        data-left-participant={leftParticipant}
        data-frame-padding-left={border.left}
        data-frame-padding-right={border.right}
        className="group fragment fragment-section section border-skin-fragment rounded"
        style={fragmentStyle}
      >
        <div className="segment">
          {props.commentObj.text && (
            <Comment comment={props.comment} commentObj={props.commentObj} />
          )}
          <div className="header bg-skin-fragment-header text-skin-fragment-header leading-4 rounded-t relative">
            <Numbering number={props.number} />
            <div className="name font-semibold p-1 border-b">
              <label className="p-0">
                <CollapseButton
                  label={label}
                  collapsed={collapsed}
                  onClick={toggleCollapse}
                  style={props.commentObj.messageStyle}
                  className={cn(props.commentObj.messageClassNames)}
                />
              </label>
            </div>
          </div>
        </div>

        <div className={collapsed ? "hidden" : ""}>
          <div className="segment">
            <div className="text-skin-fragment flex"></div>
            {blockInSection && (
              <Block
                origin={leftParticipant}
                style={{ paddingLeft: `${paddingLeft}px` }}
                context={blockInSection}
                number={props.number}
              />
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
