// src/components/DiagramFrame/SeqDiagram/LifeLineLayer/LifeLineLayer.tsx
import {
  coordinatesAtom,
  modeAtom,
  participantsAtom,
  RenderMode,
} from "@/store/Store";
import { useAtomValue } from "jotai";
import { LifeLine } from "./LifeLine";
import { LifeLineGroup } from "./LifeLineGroup";
import { Fragment, useMemo } from "react";
import { _STARTER_ } from "@/parser/OrderedParticipants";
import { blankParticipant } from "@/parser/Participants";
import { GroupContext, ParticipantContext, Participants } from "@/parser";

export const LifeLineLayer = (props: {
  context: any;
  leftGap: number;
  renderParticipants?: boolean;
  renderLifeLine?: boolean;
}) => {
  const mode = useAtomValue(modeAtom);
  const coordinates = useAtomValue(coordinatesAtom);
  const participants = useAtomValue(participantsAtom);

  const starterParticipant = useMemo(() => {
    const names = coordinates.orderedParticipantNames();
    if (names.length === 0) return null;
    const firstName = names[0];
    if (firstName === _STARTER_) {
      return {
        ...blankParticipant,
        name: _STARTER_,
        explicit: false,
        isStarter: true,
      };
    }
    return null;
  }, [coordinates]);
  return (
    <div
      className="life-line-layer lifeline-layer z-30 absolute h-full flex flex-col top-0 pt-2"
      data-participant-names="participantNames"
      style={{
        minWidth: mode === RenderMode.Dynamic ? "200px" : "auto",
        width: `calc(100% - ${props.leftGap}px)`,
        pointerEvents: props.renderParticipants ? "none" : "all",
      }}
    >
      <div className="z-lifeline-container relative grow">
        {starterParticipant && !starterParticipant?.explicit && (
          <LifeLine
            entity={starterParticipant}
            className="starter"
            renderParticipants={props.renderParticipants}
            renderLifeLine={props.renderLifeLine}
          />
        )}
        {((props.context?.children as any[]) || [])
          .filter(
            (c) => c instanceof GroupContext || c instanceof ParticipantContext,
          )
          .map((child, index) => (
            <Fragment key={index}>
              {child instanceof GroupContext && (
                <LifeLineGroup
                  key={index}
                  context={child}
                  renderParticipants={props.renderParticipants}
                  renderLifeLine={props.renderLifeLine}
                />
              )}
              {child instanceof ParticipantContext && (
                <LifeLine
                  key={index}
                  entity={Participants(child).First()}
                  renderParticipants={props.renderParticipants}
                  renderLifeLine={props.renderLifeLine}
                />
              )}
            </Fragment>
          ))}
        {participants.ImplicitArray().map((entity: any) => (
          <LifeLine
            key={entity.name}
            entity={entity}
            renderParticipants={props.renderParticipants}
            renderLifeLine={props.renderLifeLine}
          />
        ))}
      </div>
    </div>
  );
};

// src/components/DiagramFrame/SeqDiagram/LifeLineLayer/LifeLineLayer.vue
<template>
  <div
    class="life-line-layer lifeline-layer absolute h-full flex flex-col pt-8 top-0"
    :style="{ 'min-width': '200px', pointerEvents: renderParticipants ? 'none' : 'all' }"
  >
    <div class="container relative grow">
      <life-line
        v-if="starterOnTheLeft"
        :entity="starterParticipant"
        class="starter"
        :class="{ invisible: invisibleStarter }"
        :renderParticipants="renderParticipants"
      />
      <template v-for="(child, index) in explicitGroupAndParticipants">
        <life-line-group
          :key="index"
          v-if="child instanceof GroupContext"
          :context="child"
          :renderParticipants="renderParticipants"
        />
        <life-line
          :key="index"
          v-if="child instanceof ParticipantContext"
          :entity="getParticipantEntity(child)"
          :renderParticipants="renderParticipants"
        />
      </template>
      <life-line
        v-for="entity in implicitParticipants"
        :key="entity.name"
        :entity="entity"
        :renderParticipants="renderParticipants"
      />
    </div>
  </div>
</template>


<script>
import parentLogger from '../../../../logger/logger';
import { GroupContext, ParticipantContext, Participants } from '../../../../parser';
import { mapGetters, mapMutations } from 'vuex';
import LifeLine from './LifeLine.vue';
import LifeLineGroup from './LifeLineGroup.vue';
const logger = parentLogger.child({ name: 'LifeLineLayer' });

export default {
  name: 'life-line-layer',
  props: ['context', 'renderParticipants'],
  computed: {
    ...mapGetters(['participants', 'GroupContext', 'ParticipantContext', 'centerOf']),
    invisibleStarter() {
      return this.starterParticipant.name === '_STARTER_';
    },
    starterParticipant() {
      return this.participants.Starter();
    },
    starterOnTheLeft() {
      return !this.starterParticipant.explicit;
    },
    implicitParticipants() {
      return this.participants.ImplicitArray();
    },
    explicitGroupAndParticipants() {
      return this.context?.children.filter((c) => {
        const isGroup = c instanceof GroupContext;
        const isParticipant = c instanceof ParticipantContext;
        return isGroup || isParticipant;
      });
    },
  },
  methods: {
    ...mapMutations(['increaseGeneration']),
    getParticipantEntity(ctx) {
      return Participants(ctx).First();
    },
  },
  updated() {
    logger.debug('LifeLineLayer updated');
  },
  mounted() {
    logger.debug('LifeLineLayer mounted');
  },
  components: {
    LifeLine,
    LifeLineGroup,
  },
};
</script>
